services:
  - type: web
    name: facerecog-prod-backend
    env: node
    plan: free
    buildCommand: yarn
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: face-recognition
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true

databases:
  - name: face-recognition
    plan: free
